remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Nagadeepa's DataScience Portfolio
description: Here are the overview of some of my datascience projects 
